/** Section "Descubrimiento de candidatos": how to find new people. */
import { numbered, paragraphs, quotedList } from "../format/markdown";
import type { PromptContext } from "../types/prompt";
import type { Term } from "../types/term";

export const intro = (ctx: PromptContext): string => `Buscá personas que no estén en la lista de excluidos de la sección ${ctx.sectionNumber("exclusions")}.`;

export const FUNDS =
  "Recorré fondo por fondo los fondos especialistas en infraestructura y los de primer nivel, buscando socios hispanohablantes cuyo foco " +
  "personal sea infraestructura de IA, dev tools, infraestructura de datos, ciberseguridad, infraestructura enterprise, open source o deep " +
  "tech de frontera. Buscá también fondos nuevos de 2024-2026 enfocados en IA, agentes, infraestructura, cuántica, semiconductores, " +
  "ciberseguridad o developer tools; solo GPs; y angels técnicos: fundadores y CTOs que firman cheques en deep tech.";

/** Example search queries, in both languages. */
export const QUERIES = [
  "Venture capital deep tech España general partner",
  "Venture capital deep tech Estados unidos general partner",
  "Venture capital deep tech San francisco general partner",
  "Latino venture capital deep tech Estados unidos general partner",
  "Latino venture capital deep tech San francisco general partner",
  "Venture capital deep tech México general partner",
  "Venture capital deep tech Argentina general partner",
  "Venture capital deep tech árabe general partner",
  "Venture capital deep tech España principal",
  "Venture capital deep tech Estados unidos principal",
  "Venture capital deep tech San francisco principal",
  "Latino venture capital deep tech Estados unidos principal",
  "Latino venture capital deep tech San francisco principal",
  "Venture capital deep tech México principal",
  "Venture capital deep tech Argentina principal",
  "Venture capital deep tech árabe principal",
  "Venture capital deep tech España partner",
  "Venture capital deep tech Estados unidos partner",
  "Venture capital deep tech San francisco partner",
  "Latino venture capital deep tech Estados unidos partner",
  "Latino venture capital deep tech San francisco partner",
  "Venture capital deep tech México partner",
  "Venture capital deep tech Argentina partner",
  "Venture capital deep tech árabe partner",
  "Fondo deep tech España",
  "Fondo capital deep tech Estados unidos",
  "Fondo capital deep tech San francisco",
  "Latino fondo capital deep tech Estados unidos",
  "Latino fondo capital deep tech San francisco",
  "Fondo capital deep tech México",
  "Fondo capital deep tech Argentina",
  "Fondo capital deep tech árabe",
  "Inversor angel deep tech España",
  "Inversor angel deep tech Estados unidos",
  "Inversor angel deep tech San francisco",
  "Latino inversor angel deep tech Estados unidos",
  "Latino inversor angel deep tech San francisco",
  "Inversor angel deep tech México",
  "Inversor angel deep tech Argentina",
  "Inversor angel deep tech árabe",
  "Angel investor deep tech Spain",
  "Angel investor deep tech United states",
  "Latino angel investor deep tech San Francisco",
  "Latino angel investor deep tech United states",
  "Angel investor deep tech San Francisco",
  "Angel investor deep tech México",
  "Angel investor deep tech Argentina",
  "Angel investor deep tech arab",
  "Venture capital dev tools España principal",
  "Venture capital dev tools Estados unidos principal",
  "Venture capital dev tools San francisco principal",
  "Latino venture capital dev tools Estados unidos principal",
  "Latino venture capital dev tools San francisco principal",
  "Venture capital dev tools México principal",
  "Venture capital dev tools Argentina principal",
  "Venture capital dev tools árabe principal",
  "Venture capital dev tools España general partner",
  "Venture capital dev tools Estados unidos general partner",
  "Venture capital dev tools San francisco general partner",
  "Latino venture capital dev tools Estados unidos general partner",
  "Latino venture capital dev tools San francisco general partner",
  "Venture capital dev tools México general partner",
  "Venture capital dev tools Argentina general partner",
  "Venture capital dev tools árabe general partner",
  "Venture capital dev tools España partner",
  "Venture capital dev tools Estados unidos partner",
  "Venture capital dev tools San francisco partner",
  "Latino venture capital dev tools Estados unidos partner",
  "Latino venture capital dev tools San francisco partner",
  "Venture capital dev tools México partner",
  "Venture capital dev tools Argentina partner",
  "Venture capital dev tools árabe partner",
  "Fondo dev tools España",
  "Fondo capital dev tools Estados unidos",
  "Fondo capital dev tools San francisco",
  "Latino fondo capital dev tools Estados unidos",
  "Latino fondo capital dev tools San francisco",
  "Fondo capital dev tools México",
  "Fondo capital dev tools Argentina",
  "Fondo capital dev tools árabe",
  "Inversor angel dev tools España",
  "Inversor angel dev tools Estados unidos",
  "Inversor angel dev tools San francisco",
  "Latino inversor angel dev tools Estados unidos",
  "Latino inversor angel dev tools San francisco",
  "Inversor angel dev tools México",
  "Inversor angel dev tools Argentina",
  "Inversor angel dev tools árabe",
  "Angel investor dev tools Spain",
  "Angel investor dev tools United states",
  "Latino angel investor dev tools San Francisco",
  "Latino angel investor dev tools United states",
  "Angel investor dev tools San Francisco",
  "Angel investor dev tools México",
  "Angel investor dev tools Argentina",
  "Angel investor dev tools arab",
  "Venture capital developer tools España principal",
  "Venture capital developer tools Estados unidos principal",
  "Venture capital developer tools San francisco principal",
  "Latino venture capital developer tools Estados unidos principal",
  "Latino venture capital developer tools San francisco principal",
  "Venture capital developer tools México principal",
  "Venture capital developer tools Argentina principal",
  "Venture capital developer tools árabe principal",
  "Venture capital developer tools España general partner",
  "Venture capital developer tools Estados unidos general partner",
  "Venture capital developer tools San francisco general partner",
  "Latino venture capital developer tools Estados unidos general partner",
  "Latino venture capital developer tools San francisco general partner",
  "Venture capital developer tools México general partner",
  "Venture capital developer tools Argentina general partner",
  "Venture capital developer tools árabe general partner",
  "Venture capital developer tools España partner",
  "Venture capital developer tools Estados unidos partner",
  "Venture capital developer tools San francisco partner",
  "Latino venture capital developer tools Estados unidos partner",
  "Latino venture capital developer tools San francisco partner",
  "Venture capital developer tools México partner",
  "Venture capital developer tools Argentina partner",
  "Venture capital developer tools árabe partner",
  "Fondo developer tools España",
  "Fondo capital developer tools Estados unidos",
  "Fondo capital developer tools San francisco",
  "Latino fondo capital developer tools Estados unidos",
  "Latino fondo capital developer tools San francisco",
  "Fondo capital developer tools México",
  "Fondo capital developer tools Argentina",
  "Fondo capital developer tools árabe",
  "Inversor angel developer tools España",
  "Inversor angel developer tools Estados unidos",
  "Inversor angel developer tools San francisco",
  "Latino inversor angel developer tools Estados unidos",
  "Latino inversor angel developer tools San francisco",
  "Inversor angel developer tools México",
  "Inversor angel developer tools Argentina",
  "Inversor angel developer tools árabe",
  "Angel investor developer tools Spain",
  "Angel investor developer tools United states",
  "Latino angel investor developer tools San Francisco",
  "Latino angel investor developer tools United states",
  "Angel investor developer tools San Francisco",
  "Angel investor developer tools México",
  "Angel investor developer tools Argentina",
  "Angel investor developer tools arab",
  "Venture capital infraestructura IA España principal",
  "Venture capital infraestructura IA Estados unidos principal",
  "Venture capital infraestructura IA San francisco principal",
  "Latino venture capital infraestructura IA Estados unidos principal",
  "Latino venture capital infraestructura IA San francisco principal",
  "Venture capital infraestructura IA México principal",
  "Venture capital infraestructura IA Argentina principal",
  "Venture capital infraestructura IA árabe principal",
   "Venture capital infraestructura IA España general partner",
  "Venture capital infraestructura IA Estados unidos general partner",
  "Venture capital infraestructura IA San francisco general partner",
  "Latino venture capital infraestructura IA Estados unidos general partner",
  "Latino venture capital infraestructura IA San francisco general partner",
  "Venture capital infraestructura IA México general partner",
  "Venture capital infraestructura IA Argentina general partner",
  "Venture capital infraestructura IA árabe general partner",
   "Venture capital infraestructura IA España partner",
  "Venture capital infraestructura IA Estados unidos partner",
  "Venture capital infraestructura IA San francisco partner",
  "Latino venture capital infraestructura IA Estados unidos partner",
  "Latino venture capital infraestructura IA San francisco partner",
  "Venture capital infraestructura IA México partner",
  "Venture capital infraestructura IA Argentina partner",
  "Venture capital infraestructura IA árabe partner",
  "Fondo infraestructura IA España",
  "Fondo capital infraestructura IA Estados unidos",
  "Fondo capital infraestructura IA San francisco",
  "Latino fondo capital infraestructura IA Estados unidos",
  "Latino fondo capital infraestructura IA San francisco",
  "Fondo capital infraestructura IA México",
  "Fondo capital infraestructura IA Argentina",
  "Fondo capital infraestructura IA árabe",
  "Inversor angel infraestructura IA España",
  "Inversor angel infraestructura IA Estados unidos",
  "Inversor angel infraestructura IA San francisco",
  "Latino inversor angel infraestructura IA Estados unidos",
  "Latino inversor angel infraestructura IA San francisco",
  "Inversor angel infraestructura IA México",
  "Inversor angel infraestructura IA Argentina",
  "Inversor angel infraestructura IA árabe",
  "Angel investor infraestructura IA Spain",
  "Angel investor infraestructura IA United states",
  "Latino angel investor infraestructura IA San Francisco",
  "Latino angel investor infraestructura IA United states",
  "Angel investor infraestructura IA San Francisco",
  "Angel investor infraestructura IA México",
  "Angel investor infraestructura IA Argentina",
  "Angel investor infraestructura IA arab",
  "Venture capital infra IA España principal",
  "Venture capital infra IA Estados unidos principal",
  "Venture capital infra IA San francisco principal",
  "Latino venture capital infra IA Estados unidos principal",
  "Latino venture capital infra IA San francisco principal",
  "Venture capital infra IA México principal",
  "Venture capital infra IA Argentina principal",
  "Venture capital infra IA árabe principal",
  "Venture capital infra IA España general partner",
  "Venture capital infra IA Estados unidos general partner",
  "Venture capital infra IA San francisco general partner",
  "Latino venture capital infra IA Estados unidos general partner",
  "Latino venture capital infra IA San francisco general partner",
  "Venture capital infra IA México general partner",
  "Venture capital infra IA Argentina general partner",
  "Venture capital infra IA árabe general partner",
  "Venture capital infra IA España partner",
  "Venture capital infra IA Estados unidos partner",
  "Venture capital infra IA San francisco partner",
  "Latino venture capital infra IA Estados unidos partner",
  "Latino venture capital infra IA San francisco partner",
  "Venture capital infra IA México partner",
  "Venture capital infra IA Argentina partner",
  "Venture capital infra IA árabe partner",
  "Fondo infra IA España",
  "Fondo capital infra IA Estados unidos",
  "Fondo capital infra IA San francisco",
  "Latino fondo capital infra IA Estados unidos",
  "Latino fondo capital infra IA San francisco",
  "Fondo capital infra IA México",
  "Fondo capital infra IA Argentina",
  "Fondo capital infra IA árabe",
  "Inversor angel infra IA España",
  "Inversor angel infra IA Estados unidos",
  "Inversor angel infra IA San francisco",
  "Latino inversor angel infra IA Estados unidos",
  "Latino inversor angel infra IA San francisco",
  "Inversor angel infra IA México",
  "Inversor angel infra IA Argentina",
  "Inversor angel infra IA árabe",
  "Angel investor infra IA Spain",
  "Angel investor infra IA United states",
  "Latino angel investor infra IA San Francisco",
  "Latino angel investor infra IA United states",
  "Angel investor infra IA San Francisco",
  "Angel investor infra IA México",
  "Angel investor infra IA Argentina",
  "Angel investor infra IA arab",
];

export const queries = (): string => `Buscá en español y en inglés, variando muchas consultas. Ejemplos: ${quotedList(QUERIES)}.`;

/** Where to look, by scope. Only sources that exist. Rendered as a sub-list under the numbered item. */
export const SOURCE_GROUPS: { scope: string; items: string[] }[] = [
  {
    scope: "Datos y directorios de inversores",
    items: [
      "Crunchbase",
      "PitchBook",
      "Dealroom",
      "Tracxn",
      "Signal NFX",
      "OpenVC (directorio de inversores filtrable por tesis)",
      "AngelList",
      "Landscape.vc",
      "LinkedIn a través de buscadores",
      "X/Twitter",
    ],
  },
  {
    scope: "Asociaciones y redes de inversores",
    items: [
      "ASCRI (Asociación Española de Capital, Crecimiento e Inversión) y su directorio de socios",
      "AEBAN (Asociación Española de Business Angels)",
      "AMEXCAP (Asociación Mexicana de Capital Privado)",
      "LAVCA (Association for Private Capital Investment in Latin America) y su directorio",
      "LatinxVC y su informe State of Latinx VC",
      "VC Include",
      "Endeavor (Miami, México, España)",
      "Keiretsu Forum España",
      "BigBan Angels",
      "ESADE BAN",
      "IESE Business Angels",
    ],
  },
  {
    scope: "España",
    items: [
      "Dealflow.es",
      "El Referente",
      "Startupxplore",
      "Novobrief",
      "Loogic",
      "Expansión",
      "Cinco Días",
      "El Español (Invertia y D+I)",
      "Business Insider España",
      "Emprendedores",
      "South Summit y Spain Tech Week (listas de inversores asistentes)",
    ],
  },
  {
    scope: "México",
    items: ["Contxto", "Whitepaper.mx", "Expansión (México)", "El Economista (México)", "El Financiero Bloomberg", "Startupeable", "MassChallenge México", "Endeavor México"],
  },
  {
    scope: "Latinos en San Francisco y Silicon Valley",
    items: [
      "Techqueria",
      "Latinas in Tech",
      "Stanford Latino Entrepreneurship Initiative (SLEI) y LBAN",
      "Latino Community Foundation",
      "Latino Startup Alliance",
      "Silicon Valley Latino",
      "L'Attitude (conferencia)",
      "las páginas de equipo de los fondos de Sand Hill Road y San Francisco, buscando socios de origen hispano o latinoamericano",
    ],
  },
  {
    scope: "Latinos en Estados Unidos en general",
    items: [
      "Bloomberg Línea",
      "Forbes México y Forbes Centroamérica",
      "Latino Leaders",
      "Hispanic Executive",
      "US Hispanic Chamber of Commerce",
      "Google for Startups Latino Founders Fund (mentores e inversores)",
      "Crunchbase News (listas de inversores y fundadores latinos)",
      "Latitud",
    ],
  },
  {
    scope: "Mundo árabe: hispanohablantes en el Golfo y cobertura en español",
    items: [
      "Atalayar",
      "El Correo del Golfo",
      "Casa Árabe",
      "ICEX (oficinas en Dubái y Riad; informes sobre inversores del Golfo)",
      "MAGNiTT (datos de venture capital en MENA)",
      "Wamda",
      "Hub71 (Abu Dabi) y DIFC Innovation Hub (Dubái)",
      "comunidades de españoles y latinos en Dubái, Abu Dabi y Riad en LinkedIn",
    ],
  },
  {
    scope: "Podcasts y newsletters",
    items: ["20VC", "Invest Like the Best", "Itnig", "Kapital", "Cracks (Oso Trava)", "Dealflow.es", "Latitud", "Startupeable", "newsletters y blogs propios de los inversores"],
  },
];

export const sources = (): string => `Fuentes de descubrimiento, por ámbito:\n${SOURCE_GROUPS.map((group) => `   - ${group.scope}: ${group.items.join(", ")}.`).join("\n")}`;

export const NOTES =
  "Para cada candidato anotá origen o evidencia de español, foco, etapa y ticket, formación técnica, por qué encaja y confianza. " +
  'Sé honesto: si no podés confirmar la fluidez en español, decilo ("origen sólo, fluidez no confirmada"). No rellenes con generalistas ' +
  "de consumo o fintech. Llevá una lista de considerados y rechazados con el motivo, para no volver a investigarlos.";

export const discovery: Term = {
  id: "discovery",
  title: () => "Descubrimiento de candidatos",
  render: (ctx) => paragraphs(intro(ctx), numbered([FUNDS, queries(), sources(), NOTES])),
};
